[web]
  port = 8910
  apiProxyPath = "/.netlify/functions"
  includeEnvironmentVariables = ['GA_ID', 'LOCK_EDIT', 'AUTH0_DOMAIN', 'AUTH0_SECRET', 'AUTH0_CLIENT_ID', 'AUTH0_AUDIENCE']
[api]
  port = 8911
[browser]
  open = true