[web]
  port = 8910
  apiProxyPath = "/.netlify/functions"
  includeEnvironmentVariables = ['GA_ID', 'AUTH0_DOMAIN', 'AUTH0_SECRET', 'AUTH0_CLIENT_ID', 'AUTH0_AUDIENCE', 'AUTH0_NAMESPACE', 'REDIRECT_URL']
[api]
  port = 8911
[browser]
  open = true